global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_app_monitoring'
    metrics_path: '/health'
    scrape_interval: 5s
    static_configs:
      - targets: ['web:3000']
